version: '3'

services:
  proxy:
    image: nginx:1.11
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/data/static/
  web:
    image: php:7.4-apache
    command: "/bin/sh -c 'apt-get update && 
      docker-php-ext-install mysqli && 
      exec apache2-foreground &&
      apache2ctl configtest &&
      apache2ctl graceful &&
      apt-get install libaprutil1-dbd-mysql -y &&
      a2enmod dbd &&
      a2enmod authn_dbd &&
      a2enmod socache_shmcb &&
      a2enmod authn_socache &&
      service apache2 restart foreground &&
      apache2ctl -M'"
    volumes:
      - ./dynamic:/var/www/html
    restart: always
  db:
    image: 'mysql:latest'
    volumes: 
      - ./init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
