version: '3'

services:
  proxy:
    image: nginx:1.11
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/static:/data/static/

  web:
    build: 
      context: .
    volumes:
      - ./src/dynamic:/var/www/html/php/
      - ./src/static/files:/var/www/files/
    restart: always

  db:
    image: 'mysql:latest'
    volumes: 
      - ./init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis
    volumes:
      - .redis/sessions/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379"

  redis-files:
    image: redis
    volumes:
      - .redis/files/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379"

  delete_files:
    image: ubuntu:latest
    volumes: 
      - ./src/static/files:/var/files/
    command: "find /var/files/ -mmin +30 -delete"
    restart: always

